Z21 pending request queue
traintastic/traintastic pull request #73
Opened 2023-06-24 21:43 UTC by gfgit

Pending request queue allows to retry sending messages after a timeout if expected reply is not received.
This also allows to detect a message is a reply to our own changes and react to it differently

See #60

2023-06-24 22:13 UTC, gfgit commented
Quick comparison with #59 approach (not fully accurate):

## **LocoCache** approach
PROS:

- Less memory footprint when number of loco is low and many messages are sent
- Can extract individual changes from `LanXLocoInfo` like change only direction or only emergency stop
  This is possible because we cache last value of direction, speed and emergency stop per each loco.
- Can somewhat detect speed trend change: user reduces speed while train is accelerating or viceversa

CONS:

- Weak logic based on heuristic. Many edge cases
- Logic is more obscure
- More memory when many loco are running
- Annoying "ignore" delay when user moves throttle right after Traintastic has updated same loco
  This is needed to avoid receiving our own reply but creates discrepancy between real loco state and cached one.

## Pending Request Queue approach

PROS:
- While logic is more complex, it's easier to understand
-  More accurate for own replies (which get then ignored)
- Expandable to other message types
- Allows re-sending a message if no reply is received so it workarounds UDP packet loss
- Logic is much more robust
- No delay needed for throttle messages

CONS:
- Can detect external changes as our own replies if messages match.
  This shouldn't be a big problem but there are at least some edge cases (see below)
- Potential risk of big memory footprint is sending a lot of messages in a fast manner
- Does not check received message order so 2 replies referring to same object can be
  detected in wrong order.
- Cannot extract individual changes because it has no track of last value

## Future work

The solution of course will be "best of both worlds". I'll try to tune both approaches to work together
and understand which one is doing what exactly and what are the edge cases left.

It already shows big improvement when simulating enormous network delays (100 ms for every message on Z21 side)
but it's not yet perfect.
It really needs testing with real hardware (which unfortunately I don't have) because different behaviors might arise

2023-06-26 21:28 UTC, reinder commented
Looking good, I really like it. Nice work! I don't own a z21 or Z21 yet so can't test it against a real one, I only have a Digikeijs DR5000 which supports the Z21 protocol.

> If you get speed 15 after speed 5 it means someone else has explicitly set speed to 15

Or that 6 .. 14 are dropped, it's UDP after all. But under normal circumstances without a high network load it probably won't happen.

Maybe you can add a debug option to log some additional info about the retries, that might be useful if we find people to do some testing with it.

p.s. As the Z21 implementation is receiving many improvements, it seems fair to me that you add a Copyright line for your name. (Don't know how this normally works...this is my first Open Source project with contributions :))

2023-11-02 17:12 UTC, gfgit commented
Rebased onto #82

2023-11-05 23:10 UTC, reinder requested changes

2023-11-05 23:10 UTC, reinder commented on server/src/hardware/protocol/z21/clientkernel.hpp
> +    void postSend(const T& message, bool wantReply = true, int customRetryCount = 0)
`customRetryCount` should be `uint8_t`, as it is assigned to `PendingRequest::retryCount` later.

2023-11-05 23:10 UTC, reinder commented on server/src/hardware/protocol/z21/clientkernel.hpp
> +    void send(const Message& message, bool wantReply = true, int customRetryCount = 0);
`customRetryCount` should be `uint8_t`, as it is assigned to `PendingRequest::retryCount` later.

2023-11-05 23:10 UTC, reinder commented on server/src/hardware/protocol/z21/messages.cpp
> +  switch (message.header())
please indent `case` statements, it improves readability.

2023-11-05 23:10 UTC, reinder commented on server/src/hardware/protocol/z21/messages.hpp
> +    CheckDb0       = 1,
use `1 << 0` ? (then the all have the same style :)

2023-11-05 23:10 UTC, reinder commented on server/src/hardware/protocol/z21/messages.hpp
> +  };
Why does one element have `Priority` in it and the other don't have it?

Change it to `enum class Priority : uint8_t`? Then the values are scoped :)

2023-11-05 23:10 UTC, reinder commented on server/src/hardware/protocol/z21/messages.hpp
> +  enum Flags
`enum class`?

2023-11-05 23:10 UTC, reinder commented on server/src/hardware/protocol/z21/messages.hpp
> +  inline Priority getPriority() const
remove `get` for getter, the Traintastic codebase style doesn't do that.

2023-11-05 23:10 UTC, reinder commented on server/src/hardware/protocol/z21/messages.hpp
> +  inline void setPriority(Priority priority)
as the above is change, the argument name causes a *shadow* warning, that's why the common practice in the Traintastic codebase is to use `value` as name for the setter argument.

2023-11-06 00:54 UTC, gfgit commented on server/src/hardware/protocol/z21/messages.cpp
> +  switch (message.header())
We should really add a clang format file because it's too easy to forget about these things. Plus my editor automatically does formatting in a different style so it messes up every time and I need to manually adjust the damage.

2023-11-13 21:39 UTC, reinder commented on server/src/hardware/protocol/z21/messages.cpp
> +  switch (message.header())
yeah, clang-format would really help, I made one some time ago, that was working quiet well. There were a few issues, please remember me again if I forget :)

2024-07-03 20:46 UTC, gfgit commented
I now have built a Z21 with ESP32 and did some initial tests. Pending reply queue is the way to go.
We will keep some bits of my old `LocoCache` and remove it's timed logic and speed trend logic which never worked right and are difficult to understand.
Also `LocoCache` should get a better name.
I will clean the code and do some more tests

2024-07-06 13:43 UTC, gfgit commented
Last commit is a fix unrelated to this PR but found when testing.
Also currently you cannot really test this PR in simulation mode because IO handler will not reply to locomotive drive messages, this is detected as UDP packet drop so messages are sent again 2 times.

2024-08-16 08:49 UTC, gfgit commented
@reinder What do you think about this?

2024-08-16 21:40 UTC, reinder commented
> Also currently you cannot really test this PR in simulation mode because IO handler will not reply to locomotive drive messages, this is detected as UDP packet drop so messages are sent again 2 times.

Can we add that in the simulation?

2024-08-17 10:12 UTC, gfgit commented
> > Also currently you cannot really test this PR in simulation mode because IO handler will not reply to locomotive drive messages, this is detected as UDP packet drop so messages are sent again 2 times.
> 
> Can we add that in the simulation?

Yes we could but since we do not cache decoder state in simulation IO handler, the reply would contain incorrect values.

2024-08-17 10:18 UTC, gfgit commented
The problem is that reply is always a `LAN_X_LOCO_INFO` which contains all loco state. So if we rely to decoder throttle change we need to put in also functions state which we do not know because we do not cache.
By putting them all to off we would break behavior of throttle widget for example because function would stay on only until a new reply is received.
If you want I can make something similar to LocoChache inside simulation IO handler to store decoder state for replies

2024-08-17 11:00 UTC, gfgit commented
Proof of concept. Not tested yet

2024-08-17 18:40 UTC, reinder commented
Looking good, it is really helpful to have proper simulation, this makes it easier to do development without hardware attached :) (We still need to test  with real hardware off course)

2024-09-23 18:53 UTC, reinder approved these changes

2024-09-23 19:37 UTC, reinder commented
@gfgit Just tested simulation mode, works nicely. Anything else we need to check? (Or can I merge it?)

2024-09-24 09:26 UTC, gfgit commented
You can merge it!

2024-09-24 16:44 UTC, merged